# Generated by Django 4.1.7 on 2023-03-15 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0014_alter_pokemon_description_alter_pokemon_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemonentity',
            old_name='title',
            new_name='pokemon',
        ),
    ]
